### ISSUE TITLE
My questions Page 

### ISSUE THREAD

**Issue by RodrigoCordovaC** [chris-baur/UA1-SO#12]
connect the database to the front end,
finish the front end

**Comment by RodrigoCordovaC** [comment]
What my question Page should show when the user has not logged in?

**Comment by c-concio** [comment]
There shouldn't be a button in the homepage for "my questions" if the user is not logged in. It should only show when the use has successfully logged in to their account.

**Comment by c-concio** [comment]
When a user who is not logged into an account tries to access the my questions page and the favorites page, the website will ask the user to login first before being able to do anything else.

**Comment by RodrigoCordovaC** [comment]
![image](https://user-images.githubusercontent.com/35608048/37104720-6c16bf98-21fb-11e8-9fa2-b0420d134cfa.png)

**Comment by c-concio** [comment]
Issue has been resolved
