### ISSUE TITLE
NewQuestion Page

### ISSUE THREAD

**Issue by RodrigoCordovaC** [chris-baur/UA1-SO#13]
connect the database to the front end.

**Comment by RodrigoCordovaC** [comment]
![error pdo](https://user-images.githubusercontent.com/35608048/37048552-3497bfbe-213c-11e8-9f1d-d4c22e2d0d9c.JPG)

**Comment by RodrigoCordovaC** [comment]
When I call the addQuestion method from question_Controller.php

**Comment by wi55em** [comment]
Database should be connected to the front end. We are able to use a session also. Let's work on this as soon as possible so to be able to add questions and see them.

**Comment by RodrigoCordovaC** [comment]
https://github.com/chris-baur/UA1-SO/pull/22
