### ISSUE TITLE
CSS not working on the footer!

### ISSUE THREAD

**Issue by toobabaig** [chris-baur/UA1-SO#4]
I made a footer for the webpage, but when I'm trying to fill in the background color etc in the css sheet, nothing happens. I have tried every other way but it still does not work!

[footer issue.zip](https://github.com/chris-baur/UA1-SO/files/1674313/footer.issue.zip)

**Comment by RodrigoCordovaC** [comment]
To change the background color of the footer, you have to change the background color of your <div class="container">. The tag <footer> inherits its css from body.

**Comment by toobabaig** [comment]
Thanks Rodrigo, that worked, but added a double background to the header.
