### ISSUE TITLE
The Search Bar is not aligned properly

### ISSUE THREAD

**Issue by wi55em** [chris-baur/UA1-SO#6]
@seifelderbi @RodrigoCordovaC The new commits has made the search bar text just above the magnifier. 
![image](https://user-images.githubusercontent.com/35816694/36011722-3f23e6fc-0d27-11e8-843f-6e781834b46a.png)

**Comment by RodrigoCordovaC** [comment]
Yeah, that is the old html, the new menu is in homepage.php

**Comment by seifelderbi** [comment]
you have to use the .php file

**Comment by seifelderbi** [comment]
we no longer use the html one

**Comment by wi55em** [comment]
Ohh ok perfect thanks ! Should we delete the .htmls ?

**Comment by seifelderbi** [comment]
no no

**Comment by wi55em** [comment]
Ok !
